/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xu_jniworddemo_MainActivity */

#ifndef _Included_com_xu_jniworddemo_MainActivity
#define _Included_com_xu_jniworddemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xu_jniworddemo_MainActivity
 * Method:    encodeInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xu_jniworddemo_MainActivity_encodeInC
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xu_jniworddemo_MainActivity
 * Method:    decodeInC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xu_jniworddemo_MainActivity_decodeInC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
